@startuml

actor User as U
participant request_n_queueManager as RQ
participant doors as D
participant cabinMovementControl as C
participant PlantModel as PM

U -> RQ : Button
RQ -> C : targetFloor
C -> PM : liftUp/liftDown
C ->RQ : goingUp/Down
PM -> C : currentFloor

C -> PM : stop
note left
when targetFLoor = currentFloor
end note
C -> D : stop(start open the doors)
D -> C : stopFinished
D -> RQ : stopFinished

RQ -> C : new targetFloor/QueueIsEmpty



@enduml