@startuml 
title Elevator State Machine
hide empty description





state "Stop" as Stop
state "Going Up" as GU
state "Going Down" as GD
state "Wait" as W

[*]-->Stop: doorsClosed
Stop -left-> GU : doorsClosed()&\ncurrentFloor < targetFloor \n & stopFinished
GU -right-> Stop : currentFloor == targetFloor OR &\n NOT doorsClosed

Stop -right-> GD : doorsClosed()&\ncurrentFloor > targetFloor \n & stopFinished
GD -left-> Stop : currentFloor == targetFloor OR &\n NOT doorsClosed

Stop -down-> W : QueueIsEmpty
W -up-> Stop : (currentFloor = targetFloor) & \n NOT QueueIsEmpty

W--> GU : doorsClosed & (currentFloor<targetFloor) \n & (NOT QueueIsEmpty)
W--> GD : doorsClosed & (currentFloor>targetFloor) \n & (NOT QueueIsEmpty)




@enduml